name: Publish Angular Package

on:
  workflow_run:
    workflows: [Chromatic]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 19

      - name: Install Angular CLI
        run: npm install -g @angular/cli
      
      - name: Install dependencies  
        run: npm ci

      - name: Build Angular Project
        run: ng build ngx-isep-dissertation-components

      - name: Publish to Npm
        run: |
            cd dist/ngx-isep-dissertation-components
            npm pack
            npm publish ngx-isep-dissertation-components-0.0.4.tgz
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}